name: aoc
version: 1.0.0

environment:
  sdk: ^3.7.0-0

dependencies:
  collection: ^1.19.1
  equatable: ^2.0.7
  meta: ^1.16.0
  quiver: ^3.2.2
  test: ^1.25.12
  timing: ^1.0.2

dev_dependencies:
  benchmark_harness: ^2.3.1
  very_good_analysis: ^7.0.0-dev.1
